### ISSUE TITLE
Data do post quebrada em tablets/mobile

### ISSUE THREAD

**Issue by augustohp** [augustohp/augustohp.github.com#2]
Melhorar como as datas dos posts devem aparecer.

**Comment by rafaelscbr** [comment]
O que você acha dessa forma?
Dependendo da sua resposta, irei alterar para tablets/mobile.
![git](https://cloud.githubusercontent.com/assets/7819032/8511988/a7932644-2305-11e5-883e-2c88f8459786.png)
